# Generated by Django 6.0.3 on 2026-04-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_deck_sub_name_userclass_deck_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="userclass",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
