# Generated by Django 6.0.3 on 2026-04-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0003_userclass_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userclass",
            name="name",
        ),
    ]
