# Generated by Django 6.0.3 on 2026-04-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0004_remove_userclass_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="application.userclass",
            ),
        ),
    ]
